"""Add CLOSED to IssueStatus enum

Revision ID: 86f91645fc7d
Revises: f7f91d984d17
Create Date: 2025-07-04 18:22:36.058652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f91645fc7d'
down_revision: Union[str, Sequence[str], None] = 'f7f91d984d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE issuestatus ADD VALUE 'CLOSED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
